In [4]:
import numpy as np

def householder_transform(x):
    """
    Computes the Householder matrix that transforms vector x into y.
    
    Args:
    x (numpy.array): The original vector.

    Returns:
    numpy.array: The Householder matrix.
    """
    v = x / np.linalg.norm(x)
    H = np.identity(len(x)) - 2 * np.outer(v, v)
    return H

# Example usage
x = np.array([1, 2, 2])  # Replace with your vector
y = np.array([0, 3,0])  # Replace with your target vector
x_plus_y = x + y
H_x = householder_transform(x)
print("Householder Matrix:\n", H_x)
H_x_plus_y = householder_transform(x_plus_y)
print("Householder Matrix:\n", H_x_plus_y)

Householder Matrix:
 [[ 0.77777778 -0.44444444 -0.44444444]
 [-0.44444444  0.11111111 -0.88888889]
 [-0.44444444 -0.88888889  0.11111111]]
Householder Matrix:
 [[ 0.93333333 -0.33333333 -0.13333333]
 [-0.33333333 -0.66666667 -0.66666667]
 [-0.13333333 -0.66666667  0.73333333]]


In [7]:
np.dot(H_x, x)

array([-1., -2., -2.])

In [8]:
np.dot(H_x_plus_y, x_plus_y)

array([-1., -5., -2.])